parameters:
    gsm_box.gateway.2n.voiceblue.class: Bestnetwork\GSMBox\Gateway\TwoN\Voiceblue\Plugin\GatewayManagerPlugin

services:
    gsm_box.gateway.2n.voiceblue:
        class: %gsm_box.gateway.2n.voiceblue.class%
        tags:  [{ name: gsm_box.gateway.plugin }]
